# @package model
defaults:
  - /model/semantic/spt.yaml

# Size of output features
_down_dim: [64]

net:
  down_pool_dim: ${eval:'[${model._point_mlp}[-1]]'}
  down_in_mlp: ${eval:'[ [${model._node_injection_dim} + ${model._point_mlp}[-1] * (not ${model.net.nano}) + ${datamodule.num_hf_segment} * (${model.net.nano} and not ${model.net.use_node_hf})] + ${model._down_dim} * ${model._mlp_depth} ]'}
  up_dim: null  # no decoder
  up_in_mlp: null
