# @package model

_target_: src.models.panoptic.PanopticSegmentationModule

# Partial spt config specifically for the instance/panoptic partitioner
partitioner:
  _target_: src.nn.instance.InstancePartitioner
  regularization: 1e-2
  x_weight: 1
  cutoff: 1
  parallel: True
  iterations: 10
  trim: False
  discrepancy_epsilon: 1e-3

# Frequency at which the partition should be computed. If lower or equal
# to 0, the partition will only be computed at the last training epoch
partition_every_n_epochs: 10

# Stuff class indices must be specified for instantiation.
# Concretely, stuff_classes is recovered from the datamodule config
stuff_classes: ${datamodule.stuff_classes}
