_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 60

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 10

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# flaot32 precision operations (torch>=2.0)
# see https://pytorch.org/docs/2.0/generated/torch.set_float32_matmul_precision.html
float32_matmul_precision: highest
