# @package datamodule
defaults:
  - /datamodule/semantic/s3dis.yaml

# point features used for training
point_hf:
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'elevation'
  - 'rgb'
  - 'pos_room'
