# @package datamodule
defaults:
  - /datamodule/semantic/s3dis_with_stuff.yaml

# Whether the dataset produces instance labels. In any case, the
# instance labels will be preprocessed, if any. However, `instance: False`
# will avoid unwanted instance-related I/O operations, to save memory
instance: True

# Specify whether S3DIS should have only 'thing' classes (default) or if
# 'ceiling', 'wall', and 'floor' should be treated as 'stuff'
with_stuff: True

# For now, we also need to specify the stuff labels here, not for the
# datamodule, but rather for the model config to catch
stuff_classes: [0, 1, 2]

# Instantiation parameters. These are used for instance/panoptic
# segmentation but will be skipped for semantic segmentation.
# NB: setting instance_level < 0 will skip OnTheFlyInstanceGraph
instance_level: 1
instance_adjacency_mode: 'radius'
instance_k_max: 30
instance_radius: 0.1
instance_centroid_mode: 'iou'
instance_centroid_level: 1
instance_smooth_affinity: True
min_instance_size: 100
