defaults:
  - default.yaml

# Partial spt config specifically for the encoder
net:
  down_dim: ${model._d}
  down_pool_dim: ${eval:'[${model._p}[-1]] + ${model._d}[:-1]'}
  down_in_mlp: ${eval:'[ [${model._d_x} + ${model._p}[-1] * (not ${model.net.nano})] + [${model._d}[0]] * ${model._d_r}, [${model._d_x} + ${model._d}[0]] + [${model._d}[1]] * ${model._d_r}, [${model._d_x} + ${model._d}[1]] + [${model._d}[2]] * ${model._d_r}, [${model._d_x} + ${model._d}[2]] + [${model._d}[3]] * ${model._d_r} ]'}
  down_out_mlp: null
  down_mlp_drop: null
  down_num_heads: 16
  down_num_blocks: 3
  down_ffn_ratio: 1
  down_residual_drop: null
  down_attn_drop: null
  down_drop_path: null
  down_inject_pos: True  # append segment position features (or more depending on pos_injection and point_pos_injection_x_dim)
  down_inject_x: True  # append handcrafted segment features
  down_pos_injection_x_dim: null
