defaults:
  - default.yaml

# Partial NEST config specifically for the 'last' modules after the
# 'small' nodes branch merge
net:
  last_dim: ${eval:'${model._u}[-1]'}
  last_in_mlp: ${eval:'[${model._u_x} + ${model._u}[-1]] + [${model.net.last_dim}] * ${model._u_r}'}
  last_out_mlp: null
  last_mlp_drop: ${model.net.up_mlp_drop}
  last_num_heads: ${model.net.up_num_heads}
  last_num_blocks: ${model.net.up_num_blocks}
  last_ffn_ratio: ${model.net.up_ffn_ratio}
  last_residual_drop: ${model.net.up_residual_drop}
  last_attn_drop: ${model.net.up_attn_drop}
  last_drop_path:  ${model.net.up_drop_path}
  last_inject_pos: ${model.net.up_inject_pos}
  last_pos_injection_x_dim: ${model.net.up_pos_injection_x_dim}
