defaults:
  - default.yaml

# Partial spt config specifically for the point encoder
net:
  nano_dim: null
  nano_in_mlp: ${eval:'[${model._nano_x}] + [${model.net.nano_dim}] * ${model._d_r} if ${model.net.nano_dim} else None'}
  nano_out_mlp: ${model.net.down_out_mlp}
  nano_mlp_drop: ${model.net.down_mlp_drop}
  nano_num_heads: ${model.net.down_num_heads}
  nano_num_blocks: ${model.net.down_num_blocks}
  nano_ffn_ratio: ${model.net.down_ffn_ratio}
  nano_residual_drop: ${model.net.down_residual_drop}
  nano_attn_drop: ${model.net.down_attn_drop}
  nano_drop_path: ${model.net.down_drop_path}
  nano_inject_pos: ${model.net.down_inject_pos}  # append segment position features (or more depending on pos_injection and point_pos_injection_x_dim)
  nano_inject_x: ${model.net.down_inject_x}  # append handcrafted segment features
  nano_pos_injection_x_dim: ${model.net.down_pos_injection_x_dim}
