defaults:
  - default.yaml

# Partial spt config specifically for the point encoder
net:
  point_mlp: ${eval:'[${model._p_x}] + ${model._p}'}
  point_drop: null
  point_pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  point_pos_injection_x_dim: null
  point_cat_diameter: False
  point_log_diameter: ${model.net.log_diameter}
