defaults:
  - default.yaml

# Partial NEST config specifically for the decoder
net:
  up_dim: ${model._u}
  up_in_mlp: ${eval:'[ [${model._u_x} + ${model._d}[-1] + ${model._d}[-2]] + [${model._u}[0]] * ${model._u_r}, [${model._u_x} + ${model._u}[0] + ${model._d}[-3]] + [${model._u}[1]] * ${model._u_r}, [${model._u_x} + ${model._u}[1] + ${model._d}[-4]] + [${model._u}[2]] * ${model._u_r} ]'}
  up_out_mlp: ${model.net.down_out_mlp}
  up_mlp_drop: ${model.net.down_mlp_drop}
  up_num_heads: ${model.net.down_num_heads}
  up_num_blocks: ${model.net.down_num_blocks}
  up_ffn_ratio: ${model.net.down_ffn_ratio}
  up_residual_drop: ${model.net.down_residual_drop}
  up_attn_drop: ${model.net.down_attn_drop}
  up_drop_path: ${model.net.down_drop_path}
  up_inject_pos: ${model.net.down_inject_pos}  # appends position features = (3) or more depending on pos_injection and point_pos_injection_x_dim
  up_inject_x: ${model.net.down_inject_x}
  up_pos_injection_x_dim: ${model.net.down_pos_injection_x_dim}
