_target_: src.models.segmentation.PointSegmentationModule

num_classes: 15  # this is for KITTI360 num_classes
pointwise_loss: True
weighted_loss: True

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.01
  weight_decay: 1e-4

scheduler:
  _target_: src.optim.CosineAnnealingLRWithWarmup
  _partial_: True
  T_max: 180
  eta_min: 1e-6
  warmup_init_lr: 1e-6
  num_warmup: 20
  warmup_strategy: 'cos'

criterion:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.0

net: ???
