defaults:
  - default.yaml

net:
  _target_: src.models.components.hpointnet.HPointNet
  point_mlp: [12, 32, 64, 128]
  down_mlp: [[133, 64, 64], [69, 64, 64], [69, 64, 64], [69, 64, 64]]
  up_mlp: [[131, 64, 64], [131, 64, 64], [131, 64, 64]]
  point_drop: null
  down_drop: null
  up_drop: null
  down_inject_pos: True
  down_inject_x: True
  up_inject_pos: True
  up_inject_x: False
  point_pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  point_pos_injection_x_dim: null
  point_cat_diameter: True
  pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  cat_diameter: True
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
