defaults:
  - default.yaml

net:
  _target_: src.models.components.hpointnet.HPointNet
  point_mlp: [11, 32, 64, 128]
  down_mlp: [[147, 128, 128], [147, 128, 128], [147, 128, 128], [147, 128, 128]]
  up_mlp: [[259, 128, 128], [259, 128, 128], [259, 256, 256]]
  point_drop: null
  down_drop: null
  up_drop: null
  down_inject_pos: True
  down_inject_x: True
  up_inject_pos: True
  up_inject_x: False
  point_pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  point_pos_injection_x_dim: null
  point_cat_diameter: False
  pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  cat_diameter: False
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
