_target_: src.models.segmentation.PointSegmentationModule
num_classes: 15  # this is for KITTI360 num_classes
pointwise_loss: True
weighted_loss: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss

net:
  _target_: src.models.components.hpointnet.HPointNet
  point_mlp: [11, 32, 64, 128]
  down_mlp: [[129, 64, 64], [64, 64, 64], [64, 64, 64], [64, 64, 64]]
  up_mlp: [[128, 64, 64], [128, 64, 64], [128, 64, 64]]
  point_drop: null
  down_drop: null
  up_drop: null
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
