defaults:
  - hpointnet.yaml

net:
  _target_: src.models.components.hpointnet.HPointNet
  point_mlp: [96, 128, 128]
  down_mlp: [[129, 64, 64], [65, 64, 64], [65, 64, 64], [65, 64, 64]]
  up_mlp: [[128, 64, 64], [128, 64, 64], [128, 64, 64]]
  point_pos_injection:
    _target_: src.nn.FourierInjection
    _partial_: True
  point_pos_injection_x_dim: 8
  pos_injection:
    _target_: src.nn.FourierInjection
    _partial_: True
