defaults:
  - default.yaml

net:
  _target_: src.models.components.hpointnet.HPointNet

  point_mlp: [11, 32, 64, 128]
  point_drop: null
  point_pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  point_pos_injection_x_dim: null
  point_cat_diameter: False

  small: null
  small_point_mlp: null
  small_down_mlp: null

  down_mlp: [[147, 128, 128], [147, 128, 128], [147, 128, 128], [147, 128, 128]]
  down_drop: null
  down_inject_pos: True
  down_inject_x: True

  up_mlp: [[259, 128, 128], [259, 128, 128], [259, 256, 256]]
  up_drop: null
  up_inject_pos: True
  up_inject_x: False

  last_dim: null
  last_in_mlp: null
  last_out_mlp: null
  last_mlp_drop: null
  last_num_heads: 1
  last_num_blocks: 1
  last_ffn_ratio: 4
  last_residual_drop: null
  last_attn_drop: null
  last_drop_path: null
  last_inject_pos: True
  last_pos_injection_x_dim: null

  pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  cat_diameter: False
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
