defaults:
  - default.yaml

net:
  _target_: src.models.components.nest.NeST

  point_mlp: [11, 32, 64, 128]
  point_drop: null
  point_pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  point_pos_injection_x_dim: 8
  point_cat_diameter: False

  down_dim: 128
  down_in_mlp: [147, 128]
  down_out_mlp: null
  down_mlp_drop: null
  down_num_heads: 4
  down_num_blocks: 2
  down_ffn_ratio: 2
  down_residual_drop: null
  down_attn_drop: null
  down_drop_path: null
  down_inject_pos: True  # appends position features = (3) or more depending on pos_injection and point_pos_injection_x_dim
  down_inject_x: True  # appends (16) = diameter (1) + handcrafted superpoint features (15)
  down_pos_injection_x_dim: null

  up_dim: null
  up_in_mlp: null
  up_out_mlp: null
  up_mlp_drop: null
  up_num_heads: 1
  up_num_blocks: 1
  up_ffn_ratio: 4
  up_residual_drop: null
  up_attn_drop: null
  up_drop_path: null
  up_inject_pos: True  # appends position features = (3) or more depending on pos_injection and point_pos_injection_x_dim
  up_inject_x: False
  up_pos_injection_x_dim: null

  mlp_activation:
#    _target_: torch.nn.GELU
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
  mlp_norm:
    _target_: src.nn.FastBatchNorm1d
    _partial_: True
  qkv_bias: True
  qk_scale: null
  activation:
#    _target_: torch.nn.GELU
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
  pre_ln: True
  no_sa: False
  no_ffn: False

  pos_injection:
#    _target_: src.nn.FourierInjection
    _target_: src.nn.CatInjection
    _partial_: True
  cat_diameter: False
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  norm_mode: 'graph'

