defaults:
  - default.yaml
  - _point.yaml
  - _down.yaml
  - _up.yaml
  - _last.yaml
  - _small.yaml
  - _attention.yaml

net:
  _target_: src.models.components.nest.NeST

  node_mlp: ${eval:'[${model._d_x_raw}] + [${model._x_n_mlp}] * ${model._d_r} if ${model._x_n_mlp} else None'}
  h_edge_mlp: ${eval:'[${model._x_he_raw}] + [${model._x_ve_mlp}] * ${model._d_r} if ${model._x_ve_mlp} else None'}
  v_edge_mlp: ${eval:'[${model._x_ve_raw}] + [${model._x_ve_mlp}] * ${model._d_r} if ${model._x_ve_mlp} else None'}
  share_hf_mlps: False
  mlp_activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
  mlp_norm:
    _target_: src.nn.FastBatchNorm1d
    _partial_: True

  pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  cat_diameter: False
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  norm_mode: 'graph'

  small: null  # no branch for 'small' L1 nodes
  last_dim: null  # no modules after the 'small' nodes branch merge
