_target_: src.models.pointnet.PointNetModule
num_classes: 15  # this is for KITTI360 num_classes
pointwise_metrics: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.pointnet.PointNet
  local_channels: [10, 32, 64, 128]
  global_channels: [129, 64, 32]
  num_classes: ${model.num_classes}
