defaults:
  - default.yaml

net:
  _target_: src.models.components.pointnet.PointNet
  point_mlp: [11, 32, 64, 128]
  down_mlp: [131, 64, 32]
  point_drop: null
  down_drop: null
  pool: 'max'
  activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
