defaults:
  - default.yaml

# Size of output features
_d: 64
_u_x: null

net:
  _target_: src.models.components.nest.NeST

  point_mlp: ${eval:'[${model._p_x}] + ${model._p}'}
  point_drop: null
  point_pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  point_pos_injection_x_dim: null
  point_cat_diameter: False

  down_dim: ${model._d}
  down_in_mlp: ${eval:'[${model._d_x} + ${model._p}[-1]] + [${model._d}] * ${model._d_r}'}
  down_out_mlp: null
  down_mlp_drop: null
  down_num_heads: 16
  down_num_blocks: 3
  down_ffn_ratio: 1
  down_residual_drop: null
  down_attn_drop: null
  down_drop_path: null
  down_inject_pos: True  # append segment position features (or more depending on pos_injection and point_pos_injection_x_dim)
  down_inject_x: True  # append handcrafted segment features
  down_pos_injection_x_dim: null

  up_dim: null
  small: null
  last_dim: null

  mlp_activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
  mlp_norm:
    _target_: src.nn.FastBatchNorm1d
    _partial_: True
  activation:
    _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
  pre_ln: True
  no_sa: False
  no_ffn: False
  qk_dim: 4
  qkv_bias: True
  qk_scale: null
  scale_qk_by_neigh: True
  k_rpe: False
  q_rpe: False
  c_rpe: False
  v_rpe: False
  blocks_share_rpe: False
  heads_share_rpe: False

  pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  cat_diameter: False
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  norm_mode: 'graph'
