defaults:
  - spt.yaml

net:
  down_dim: ${eval:'${model._d}[:2]'}
  down_in_mlp: ${eval:'[ [${model._d_x} + ${model._p}[-1] * (not ${model.net.nano}) + ${datamodule.num_hf_segment} * ${model.net.nano}] + [${model._d}[0]] * ${model._d_r}, [${model._d_x} + ${model._d}[0]] + [${model._d}[1]] * ${model._d_r} ]'}
  up_dim: ${eval:'${model._u}[:1]'}
  up_in_mlp: ${eval:'[ [${model._u_x} + ${model._d}[-1] + ${model._d}[-2]] + [${model._u}[0]] * ${model._u_r} ]'}
