defaults:
  - default.yaml
  - _point.yaml
  - _down.yaml
  - _up.yaml
  - _attention.yaml

net:
  _target_: src.models.components.spt.SPT

  nano: False
  node_mlp: ${eval:'[${model._d_x_raw}] + [${model._x_n_mlp}] * ${model._d_r} if ${model._x_n_mlp} and ${model.net.down_inject_x} and ${model._d_x_raw} > 0 else None'}
  h_edge_mlp: ${eval:'[${model._x_he_raw}] + [${model._x_he_mlp}] * ${model._d_r} if ${model._x_he_mlp} else None'}
  v_edge_mlp: ${eval:'[${model._x_ve_raw}] + [${model._x_ve_mlp}] * ${model._d_r} if ${model._x_ve_mlp} else None'}
  share_hf_mlps: False
  mlp_activation:
    _target_: torch.nn.LeakyReLU
  mlp_norm:
    _target_: src.nn.GraphNorm
    _partial_: True

  pos_injection:
    _target_: src.nn.CatInjection
    _partial_: True
  cat_diameter: False
  pool: 'max'
  unpool: 'index'
  fusion: 'cat'
  norm_mode: 'graph'
