# @package _global_

defaults:
  - _self_
  - datamodule: kitti360.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: s1.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  -   optional local: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
