# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - train.yaml
  - datamodule: s3dis.yaml
  - logger: wandb_s3dis.yaml # null for default, set logger here or use command line (e.g. `python train.py logger=tensorboard`)

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True
