# Mandatory list of handcrafted features for points, segments and edges
# that will be used for partition and training. The rest of the config
# will use these to interpolate other important values
partition_hf: ???  # point features used for the partition
point_hf: ???  # point features used for training
segment_hf: ???  # segment features used for training
edge_hf: ???  # horizontal edge features used for training
v_edge_hf: ???  # vertical edge features used for training

# The number of input channels for points, segments and horizontal and
# vertical edges
num_hf_point: ${eval:'sum([${datamodule.features}[k] for k in ${datamodule.point_hf}])'}
num_hf_segment: ${eval:'sum([${datamodule.features}[k] for k in ${datamodule.segment_hf}])'}
num_hf_edge: ${eval:'sum([${datamodule.features}[k] for k in ${datamodule.edge_hf}])'}
num_hf_v_edge: ${eval:'sum([${datamodule.features}[k] for k in ${datamodule.v_edge_hf}])'}

# List of level-0 (points) and level-1+ Data keys that need to be saved
# or loaded from disk. This saves training time, loading only necessary
# data
point_save_keys: null  # level-0 keys to save on disk after preprocessing, 'null' to save all
segment_save_keys: null  # level-1+ keys to save on disk after preprocessing, 'null' to save all
point_basic_load_keys: ['pos', 'y', 'super_index', 'is_val']  # needed point attributes, other than features
segment_basic_load_keys: ['pos', 'y', 'super_index', 'sub', 'edge_index', 'edge_attr']  # needed segment attributes, other than features
point_load_keys: ${eval:'${datamodule.point_basic_load_keys} + ${datamodule.point_hf}'}  # level-0 keys to load from disk after preprocessing, 'null' to load all
segment_load_keys: ${eval:'${datamodule.segment_basic_load_keys} + ${datamodule.segment_hf}'}  # level-1+ keys to load from disk after preprocessing, 'null' to load all

# Comprehensive list of feature sizes, to be used to deduce feature size
# from name
features:
    pos: 3
    pos_room: 3
    rgb: 3
    hsv: 3
    lab: 3
    density: 1
    linearity: 1
    planarity: 1
    scattering: 1
    verticality: 1
    normal: 3
    length: 1
    surface: 1
    volume: 1
    curvature: 1
    elevation: 1
    size: 1

    log_pos: 3
    log_pos_room: 3
    log_rgb: 3
    log_hsv: 3
    log_lab: 3
    log_density: 1
    log_linearity: 1
    log_planarity: 1
    log_scattering: 1
    log_verticality: 1
    log_normal: 3
    log_length: 1
    log_surface: 1
    log_volume: 1
    log_curvature: 1
    log_elevation: 1
    log_size: 1

    mean_pos: 3
    mean_pos_room: 3
    mean_rgb: 3
    mean_hsv: 3
    mean_lab: 3
    mean_density: 1
    mean_linearity: 1
    mean_planarity: 1
    mean_scattering: 1
    mean_verticality: 1
    mean_normal: 3
    mean_length: 1
    mean_surface: 1
    mean_volume: 1
    mean_curvature: 1
    mean_elevation: 1
    mean_size: 1

    std_pos: 3
    std_pos_room: 3
    std_rgb: 3
    std_hsv: 3
    std_lab: 3
    std_density: 1
    std_linearity: 1
    std_planarity: 1
    std_scattering: 1
    std_verticality: 1
    std_normal: 3
    std_length: 1
    std_surface: 1
    std_volume: 1
    std_curvature: 1
    std_elevation: 1
    std_size: 1

    mean_off: 3
    std_off: 3
    mean_dist: 1
    angle_source: 1
    angle_target: 1
    centroid_dir: 3
    centroid_dist: 1
    normal_angle: 1
