defaults:
  - dales.yaml

# C : /50 /200 /600 ratios
# H 1: 10, 10, 10 edges
knn: 25
pcp_regularization: [0.1, 0.1, 0.1]
pcp_spatial_weight: [1e-1, 1e-2, 1e-3]
pcp_cutoff: [10, 10, 10]
graph_k_max: 30
graph_gap: [3, 10, 30]
