defaults:
  - dales.yaml

# A : /50 /400 /1500 ratios
# H 2: 20, 20, 3 edges
knn: 25
pcp_regularization: [0.1, 0.2, 0.3]
pcp_spatial_weight: [1e-1, 1e-2, 1e-3]
pcp_cutoff: [10, 30, 100]
graph_k_max: 30
graph_gap: [5, 30, 30]
