defaults:
  - _features.yaml

_target_: null

data_dir: ${paths.data_dir}
x32: True
y_to_csr: True
x16_edge: True
in_memory: False

# Number of classes must be specified to help instantiating the model.
# Concretely, num_classes here will be passed to the DataModule and the
# Dataset upon hydra.utils.instantiate. But it will likely be ignored by
# those. Specifying num_classes in the data config actually allows the
# model config to capture it and assign the proper model output size by
# config interpolation
num_classes: ???

# Transforms
pre_transform: null
train_transform: null
val_transform: null
test_transform: null
on_device_train_transform: null
on_device_val_transform: null
on_device_test_transform: null

# Test-time augmentation
tta_runs: null
tta_val: False

# DataLoader parameters. Would be good to have them live in another file
dataloader:
    batch_size: 4
    num_workers: 4
    pin_memory: True
    persistent_workers: True
