defaults:
  - kitti360_point_hf1_segment_none.yaml

# segment-wise features computed at preprocessing
segment_mean_hf:
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'elevation'
  - 'hsv'
