defaults:
  - kitti360.yaml

# A : /10 /500 /1500 ratios
# H 2: 20, 10, 10 edges
knn: 25
pcp_regularization: [0.1, 0.2, 0.3]
pcp_spatial_weight: [1e-1, 1e-2, 1e-3]
pcp_cutoff: [10, 30, 30]
graph_gap: [1, 3, 10]
pc_tiling: 2
