defaults:
  - s3dis.yaml

# Test-time augmentation
tta_runs: 5
tta_val: True
tta:
    # Batch construction parameterization
    sample_point_min: 128
    sample_point_max: 256
    sample_segment_ratio: 0
    sample_edge_n_min: 10
    sample_edge_n_max: 25

    # Augmentations parameterization
    pos_jitter: 0
    tilt_n_rotate_phi: 0.2
    tilt_n_rotate_theta: 180
    anisotropic_scaling: 0.2
    node_feat_jitter: 0
    h_edge_feat_jitter: 0
    v_edge_feat_jitter: 0
    node_feat_drop: 0
    h_edge_feat_drop: 0
    v_edge_feat_drop: 0

# GPU-based val transforms
on_device_val_transform:
    - transform: SampleSubNodes
      params:
        low: 0
        high: 1
        n_min: ${datamodule.tta.sample_point_min}
        n_max: ${datamodule.tta.sample_point_max}
    - transform: SampleSegments
      params:
        ratio: ${datamodule.tta.sample_segment_ratio}
        by_size: False
        by_class: False
    - transform: NAGJitterKey  # before OnTheFlyHorizontalEdgeFeatures to affect RPEs
      params:
        key: 'pos'
        sigma: ${datamodule.tta.pos_jitter}
        trunc: ${datamodule.voxel}
    - transform: RandomTiltAndRotate  # before OnTheFlyHorizontalEdgeFeatures to affect RPEs
      params:
        phi: ${datamodule.tta.tilt_n_rotate_phi}
        theta: ${datamodule.tta.tilt_n_rotate_theta}
    - transform: RandomAnisotropicScale  # before OnTheFlyHorizontalEdgeFeatures to affect RPEs
      params:
        delta: ${datamodule.tta.anisotropic_scaling}
    - transform: RandomAxisFlip  # before OnTheFlyHorizontalEdgeFeatures to affect RPEs
      params:
        p: 0.5
    - transform: OnTheFlyHorizontalEdgeFeatures
      params:
        mean_off: True
        std_off: True
        mean_dist: True
        angle_source: True
        angle_target: True
        centroid_dir: True
        centroid_dist: True
        normal_angle: True
        log_length: True
        log_surface: True
        log_volume: True
        log_size: True
    - transform: OnTheFlyVerticalEdgeFeatures
      params:
        centroid_dir: True
        centroid_dist: True
        normal_angle: True
        log_length: True
        log_surface: True
        log_volume: True
        log_size: True
    - transform: SampleEdges
      params:
        level: '1+'
        n_min: ${datamodule.tta.sample_edge_n_min}
        n_max: ${datamodule.tta.sample_edge_n_max}
    - transform: NAGAddKeysToX  # adapt datamodule.feat_segment if modified
      params:
        level: '1+'
        keys: ['log_length', 'log_surface', 'log_volume', 'normal', 'log_size']
    - transform: NAGSelectColumns
      params:
        level: 0
        key: 'x'
        idx: ${datamodule.select_feat_point}
    - transform: NAGSelectColumns
      params:
        level: '1+'
        key: 'x'
        idx: ${datamodule.select_feat_segment}
    - transform: NAGSelectColumns
      params:
        level: '1+'
        key: 'edge_attr'
        idx: ${datamodule.select_feat_horizontal_edge}
    - transform: NAGSelectColumns
      params:
        level: 'all'
        key: 'v_edge_attr'
        idx: ${datamodule.select_feat_v_edge}
    - transform: NAGJitterKey
      params:
        key: 'x'
        sigma: ${datamodule.tta.node_feat_jitter}
        trunc: ${eval:'2 * ${datamodule.tta.node_feat_jitter}'}
    - transform: NAGJitterKey
      params:
        key: 'edge_attr'
        sigma: ${datamodule.tta.h_edge_feat_jitter}
        trunc: ${eval:'2 * ${datamodule.tta.h_edge_feat_jitter}'}
    - transform: NAGJitterKey
      params:
        key: 'v_edge_attr'
        sigma: ${datamodule.tta.v_edge_feat_jitter}
        trunc: ${eval:'2 * ${datamodule.tta.v_edge_feat_jitter}'}
    - transform: NAGColorAutoContrast
      params:
        level: all
        p: 0.5
        x_idx: 0
    - transform: NAGDropoutColumns
      params:
        level: 'all'
        p: ${datamodule.node_feat_drop}
        key: 'x'
    - transform: NAGDropoutColumns
      params:
        level: 'all'
        p: ${datamodule.h_edge_feat_drop}
        key: 'edge_attr'
    - transform: NAGDropoutColumns
      params:
        level: 'all'
        p: ${datamodule.v_edge_feat_drop}
        key: 'v_edge_attr'
    - transform: NAGAddSelfLoops
