defaults:
  - s3dis_b.yaml

# point features used for training
point_hf: []

# segment-wise features computed at preprocessing
segment_base_hf:
  - "log_length"
  - "log_surface"
  - "log_volume"
  - "log_size"
  - "normal"

# segment-wise features computed at preprocessing
segment_mean_hf:
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'elevation'
  - 'rgb'
