defaults:
  - s3dis.yaml

_target_: src.datamodules.s3dis_room.S3DISRoomDataModule

fold: 5
trainval: True
val_on_test: True

pre_transform:

#    - transform: DataTo
#      params:
#        device: 'cuda'
    - transform: GridSampling3D
      params:
        size: 0.03  # from SPG
        hist_key: 'y'
        hist_size: 14  # this is for S3DIS_NUM_CLASSES +1 for ignored
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: KNN
      params:
        k: 45  # from SPG
        r_max: 1
        verbose: True
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: GroundElevation
      params:
        threshold: 1.5
        scale: 4.0
    - transform: RoomPosition  # from SPG
      params:
        elevation: False
    - transform: PointFeatures
      params:
        rgb: True
        hsv: False
        lab: False
        density: False
        linearity: True
        planarity: True
        scattering: True
        verticality: True
        normal: False
        length: False
        surface: False
        volume: False
        curvature: False
        elevation: True
        pos_room: False
        k_min: 1
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: AdjacencyGraph
      params:
        k: 10  # from SPG
        w: 1  # from SPG
    - transform: ConnectIsolated
      params:
        k: 1
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: CutPursuitPartition
      params:
        regularization: [0.03, 0.07, 0.3, 0.9]  # level-1 from SPG
        spatial_weight: [5e-2, 5e-2, 5e-3, 5e-4]
        k_adjacency: 10
        cutoff: [10, 10, 80, 640]
        iterations: 15
        parallel: True
        verbose: True
    - transform: NAGTo
      params:
        device: 'cuda'
    - transform: NAGAddKeyToX
      params:
        level: 0
        keys: ['pos_room']
    - transform: SegmentFeatures
      params:
        n_max_node: 32
        n_min: 5
    - transform: EdgeFeatures
      params:
        n_max_edge: 64
        n_min: 5
        max_dist: [3, 10, 30, 100]
    - transform: NAGTo
      params:
        device: 'cpu'
