defaults:
  - s3dis.yaml

_target_: src.datamodules.s3dis_room.S3DISRoomDataModule

dataloader:
    batch_size: 8

# These parameters are not actually used by the DataModule, but are used
# here to facilitate model parameterization with config interpolation
feat_segment: 15

# Based on SPG: https://arxiv.org/pdf/1711.09869.pdf
voxel: 0.03
knn: 45
regularization: [0.03, 0.1, 0.3, 0.9]  # level-1 from SPG
spatial_weight: [5e-2, 5e-2, 5e-3, 5e-4]
cutoff: [10, 10, 80, 640]
w_adjacency: 1

dropout_segment_ratio: 0.3
select_feat_point: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # use the canonical room position
#select_feat_point: [0, 1, 2, 3, 4, 5, 6, 7]
