defaults:
  - s3dis.yaml

_target_: src.datamodules.s3dis.S3DISRoomDataModule

fold: 5
trainval: True
val_on_test: True

pre_transform: ADD ROOM GLOBAL NORMALIZATION COORDINATES !!!!

#    - transform: DataTo
#      params:
#        device: 'cuda'
    - transform: GridSampling3D
      params:
        size: 0.05
        hist_key: 'y'
        hist_size: 14  # this is for S3DIS_NUM_CLASSES +1 for ignored
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: KNN
      params:
        k: 25
        r_max: 2
        verbose: True
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: GroundElevation
      params:
        threshold: 1.5
        scale: 4.0
    - transform: RoomPosition
      params:
        elevation: False
    - transform: PointFeatures
      params:
        rgb: True
        hsv: False
        lab: False
        density: False
        linearity: True
        planarity: True
        scattering: True
        verticality: True
        normal: False
        length: False
        surface: False
        volume: False
        curvature: False
        elevation: True
        pos_room: False
        k_min: 1
    - transform: NAGAddKeyToX
      params:
        level: '0'
        keys: ['pos_room']
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: AdjacencyGraph
      params:
        k: 10
        w: -1
    - transform: ConnectIsolated
      params:
        k: 1
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: CutPursuitPartition
      params:
        regularization: [0.07, 0.3, 0.9, 1.8]
        spatial_weight: [5e-2, 5e-3, 5e-4, 5e-4]
        k_adjacency: 10
        cutoff: [10, 80, 640, 5120]
        iterations: 15
        parallel: True
        verbose: True
    - transform: NAGTo
      params:
        device: 'cuda'
    - transform: SegmentFeatures
      params:
        n_max_node: 32
        n_min: 5
    - transform: EdgeFeatures
      params:
        n_max_edge: 64
        n_min: 5
        max_dist: [3, 10, 30, 100]
    - transform: NAGTo
      params:
        device: 'cpu'
