defaults:
  - s3dis_point_none_segment_none.yaml

point_hf:
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'elevation'

# segment-wise features computed at preprocessing
segment_base_hf:
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
