defaults:
  - default.yaml

_target_: src.datamodules.s3dis.S3DISDataModule

fold: 5
trainval: True
val_on_test: True

pre_transform:

#    - transform: DataTo
#      params:
#        device: 'cuda'
    - transform: GridSampling3D
      params:
        size: 0.05
        hist_key: 'y'
        hist_size: 14  # this is for S3DIS_NUM_CLASSES +1 for ignored
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: KNN
      params:
        k: 25
        r_max: 2
        verbose: True
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: GroundElevation
      params:
        threshold: 1.5
        scale: 4.0
    - transform: PointFeatures
      params:
        rgb: True
        hsv: False
        lab: False
        density: False
        linearity: True
        planarity: True
        scattering: True
        verticality: True
        normal: False
        length: False
        surface: False
        volume: False
        curvature: False
        elevation: True
        k_min: 1
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: AdjacencyGraph
      params:
        k: 10
        w: -1
    - transform: ConnectIsolated
      params:
        k: 1
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: CutPursuitPartition
      params:
        regularization: [0.07, 0.3, 0.9, 1.8]
        spatial_weight: [5e-2, 5e-3, 5e-4, 5e-4]
        k_adjacency: 10
        cutoff: [10, 80, 640, 5120]
        iterations: 15
        parallel: True
        verbose: True
    - transform: NAGTo
      params:
        device: 'cuda'
    - transform: SegmentFeatures
      params:
        n_max_node: 32
        n_min: 5
    - transform: EdgeFeatures
      params:
        n_max_edge: 64
        n_min: 5
        max_dist: [3, 10, 30, 100]
    - transform: NAGTo
      params:
        device: 'cpu'

train_transform:
    - transform: NAGRemoveKeys  # remove any features already computed in CutPursuitPartition
      params:
        level: '1+'
        keys: [ 'linearity', 'planarity', 'scattering', 'verticality', 'curvature']
    - transform: NAGAddKeyToX
      params:
        level: '1+'
        keys: ['log_length', 'log_surface', 'log_volume', 'normal', 'log_size']
    - transform: NAGSelectColumns
      params:
        level: '1+'
        key: 'edge_attr'
        idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

val_transform: ${datamodule.train_transform}

test_transform: ${datamodule.train_transform}

on_device_train_transform:
    - transform: SampleSegments
      params:
        high: 1
        low: 0
        n_min: 32
        n_max: 128
    - transform: DropoutSegments
      params:
        ratio: [0.4, 0, 0, 0]
        by_size: False
        by_class: False
    - transform: JitterPosition
      params:
        sigma: 0.03
    - transform: JitterFeatures
      params:
        sigma: 0.01
    - transform: JitterEdgeFeatures
      params:
        sigma: 0.01
    - transform: RandomTiltAndRotate
      params:
        phi: 0.1
        theta: 180
    - transform: RandomAnisotropicScale
      params:
        delta: 0.2
    - transform: RandomAxisFlip
      params:
        p: 0.5
    - transform: NAGColorAutoContrast
      params:
        level: all
        p: 0.5
        x_idx: 0

# Should we actually sample at validation time ?
# Should we do test-time augmentations ?
on_device_val_transform:
    - transform: SampleSegments
      params:
        high: 1
        low: 0
        n_min: 128
        n_max: 256

on_device_test_transform: ${datamodule.on_device_val_transform}