defaults:
  - s3dis.yaml

# segment-wise features computed at preprocessing
segment_base_hf:
  - 'log_length'
  - 'log_surface'
  - 'log_volume'
  - 'log_size'
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'normal'

# segment features computed as the mean of point feature in each
# segment, saved with "mean_" prefix
segment_mean_hf: []
