defaults:
  - s3dis.yaml

# B : /30 /100 /500 ratios
# H 4: 25, 25, 25 edges
pcp_regularization: [0.1, 0.2, 0.7]
pcp_spatial_weight: [5e-2, 5e-2, 5e-3]
pcp_cutoff: [10, 10, 10]
graph_k_max: 30
graph_gap: [0.3, 0.5, 1]
pc_tiling: 2
