defaults:
  - s3dis.yaml

# no room pos
# no curvature
# mean pointwise geof rather than segment wise geof

segment_hf:  # segment features used for training
  - 'elevation'
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'log_length'
  - 'log_surface'
  - 'log_volume'
  - 'log_size'
  - 'normal'

# Preprocessing
pre_transform:
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: GridSampling3D  # might OOM on CUDA if voxel and GPU memory too small
      params:
        size: ${datamodule.voxel}
        hist_key: 'y'
        hist_size: ${eval:'${datamodule.num_classes} + 1'}
    - transform: KNN
      params:
        k: ${datamodule.knn}
        r_max: ${datamodule.knn_r}
        verbose: False
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: GroundElevation
      params:
        threshold: 1.5
        scale: 4.0
    - transform: PointFeatures
      params:
        rgb: True
        hsv: False
        lab: False
        density: False
        linearity: True
        planarity: True
        scattering: True
        verticality: True
        normal: False
        length: False
        surface: False
        volume: False
        curvature: False
        k_min: 1
        k_step: ${datamodule.knn_step}
        k_min_search: ${datamodule.knn_min_search}
    - transform: DataTo
      params:
        device: 'cuda'
    - transform: AdjacencyGraph
      params:
        k: ${datamodule.pcp_k_adjacency}
        w: ${datamodule.pcp_w_adjacency}
    - transform: ConnectIsolated
      params:
        k: 1
    - transform: DataTo
      params:
        device: 'cpu'
    - transform: AddKeysTo  # move some features to 'x' to be used for partition
      params:
        keys: ${datamodule.partition_hf}
        to: 'x'
        delete_after: False
    - transform: CutPursuitPartition
      params:
        regularization: ${datamodule.pcp_regularization}
        spatial_weight: ${datamodule.pcp_spatial_weight}
        k_adjacency: ${datamodule.pcp_k_adjacency}
        cutoff: ${datamodule.pcp_cutoff}
        iterations: ${datamodule.pcp_iterations}
        parallel: True
        verbose: False
    - transform: NAGRemoveKeys  # remove 'x' used for partition (features are still preserved under their respective Data attributes)
      params:
        level: 'all'
        keys: 'x'
    - transform: NAGTo
      params:
        device: 'cuda'
    - transform: SegmentFeatures
      params:
        linearity: True
        planarity: True
        scattering: True
        verticality: True
        curvature: False
        log_length: True
        log_surface: True
        log_volume: True
        normal: True
        log_size: True
        n_min: 32
        n_max: 128
        mean_keys: ['linearity', 'planarity', 'scattering', 'verticality', 'elevation']
        std_keys: []
    - transform: RadiusHorizontalGraph
      params:
        k_min: ${datamodule.graph_k_min}
        k_max: ${datamodule.graph_k_max}
        gap: ${datamodule.graph_gap}
        se_ratio: ${datamodule.graph_se_ratio}
        se_min: ${datamodule.graph_se_min}
        cycles: ${datamodule.graph_cycles}
        margin: ${datamodule.graph_margin}
        chunk_size: ${datamodule.graph_chunk}
        halfspace_filter: True
        bbox_filter: True
        target_pc_flip: True
        source_pc_sort: False
        mean_off: True
        std_off: True
        mean_dist: True
    - transform: NAGTo
      params:
        device: 'cpu'
