defaults:
  - s3dis_point_rgblps_segment_none.yaml

# segment features computed as the mean of point feature in each
# segment, saved with "std_" prefix
segment_std_hf:
  - 'linearity'
  - 'planarity'
  - 'scattering'
