defaults:
  - s3dis.yaml

# A : /50 /100 /600 ratios
# H 3: 10, 10, 10 edges
pcp_regularization: [0.03, 0.1, 0.3]
pcp_spatial_weight: [5e-2, 5e-2, 5e-3]
pcp_cutoff: [10, 10, 80]
graph_k_max: 30
graph_gap: [0.1, 0.5, 1]
pc_tiling: 2
