defaults:
  - s3dis.yaml

# segment-wise features computed at preprocessing
segment_base_hf: []

# segment features computed as the mean of point feature in each
# segment, saved with "mean_" prefix
segment_mean_hf:
  - 'pos_room'

# segment features computed as the std of point feature in each segment,
# saved with "std_" prefix
segment_std_hf: []
